name: Integrity check

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Build decks
      run: composer build

  index:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Index data.csv
      run: composer index

    - name: Check diff
      run: git diff-index --quiet HEAD -- || echo "You need to run \`composer index\`"
